version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
    ports:
      - "9090:9090"
    volumes:
      - .:/mnt
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cart
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: